server.port=8085
spring.application.name=notification-service


spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://shopeasyuser:shopeasypassword@cluster0.sszcggs.mongodb.net/?appName=Cluster0}
spring.data.mongodb.database=${MONGO_DB:notificationdb}
spring.data.mongodb.auto-index-creation=true
