server:
  port: 8082

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://shopeasyuser:shopeasypassword@cluster0.sszcggs.mongodb.net/?appName=Cluster0}
      database: orderdb

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

services:
  auth:
    base-url: ${AUTH_SERVICE_BASE_URL:http://localhost:8084}
  product:
    base-url: ${PRODUCT_SERVICE_BASE_URL:http://localhost:8084}
  supermarket:
    base-url: ${SUPERMARKET_SERVICE_BASE_URL:http://localhost:8085}
  promotion:
    base-url: ${PROMOTION_SERVICE_BASE_URL:http://localhost:8086}
  delivery:
    base-url: ${DELIVERY_SERVICE_BASE_URL:http://localhost:8087}
  notification:
    base-url: ${NOTIFICATION_SERVICE_BASE_URL:http://localhost:8088}

security:
  gateway:
    enabled: ${GATEWAY_HEADER_VALIDATION_ENABLED:true}
    header-name: ${GATEWAY_HEADER_NAME:X-Gateway-Key}
    header-value: ${GATEWAY_SHARED_KEY:change-me-order-key}
