# Auth Service Configuration
spring.application.name=auth-service
server.port=8081

# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://shopeasyuser:shopeasypassword@cluster0.sszcggs.mongodb.net/?appName=Cluster0}
spring.data.mongodb.database=${MONGO_DB:authdb}
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktZm9yLWxhdW5kcnktYXBw}
jwt.expiration-ms=86400000

# gRPC server port
grpc.server.port=9094
grpc.server.address=0.0.0.0

# Default Admin User
admin.username=${ADMIN_USERNAME:admin}
admin.email=${ADMIN_EMAIL:admin@mail.com}
admin.password=${ADMIN_PASSWORD:admin@1234}
