spring.application.name=supermarket-service
server.port=8087

# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://shopeasyuser:shopeasypassword@cluster0.sszcggs.mongodb.net/?appName=Cluster0}
spring.data.mongodb.database=${MONGO_DB:supermarketdb}
spring.data.mongodb.auto-index-creation=true
