# 1. Server Configuration
server.port=8086
spring.application.name=review-service

# 2. MongoDB Database Connection
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://shopeasyuser:shopeasypassword@cluster0.sszcggs.mongodb.net/?appName=Cluster0}
spring.data.mongodb.database=${MONGO_DB:reviewdb}
spring.data.mongodb.auto-index-creation=true